// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2pslYOStEzx5jc7R01ykl_A7CBkmEQI',
    appId: '1:116120217389:android:6c6b11d7604f545dd515a4',
    messagingSenderId: '116120217389',
    projectId: 'buzrydecloud',
    databaseURL: 'https://buzrydecloud-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buzrydecloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiDYdGmmem7kNeLTw-odK6LTgye_k-9Q',
    appId: '1:116120217389:ios:756de3b37d960e88d515a4',
    messagingSenderId: '116120217389',
    projectId: 'buzrydecloud',
    databaseURL: 'https://buzrydecloud-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buzrydecloud.appspot.com',
    androidClientId: '116120217389-89megjc697sk662v0gufanfsaaep624v.apps.googleusercontent.com',
    iosClientId: '116120217389-69m7sbkg6h2muv9un1vge3krftmpcd06.apps.googleusercontent.com',
    iosBundleId: 'ca.buzryde.driver',
    // iosBundleId: 'driver.buzryde.com',
  );

}